name: rsrnaquant
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _r-mutex=1.0.1=anacondar_1
  - alsa-lib=1.2.14=hb9d3cd8_0
  - amply=0.1.6=pyhd8ed1ab_1
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - appdirs=1.4.4=pyhd8ed1ab_1
  - argcomplete=3.6.2=pyhd8ed1ab_0
  - argparse-dataclass=2.0.0=pyhd8ed1ab_0
  - attrs=25.3.0=pyh71513ae_0
  - bedtools=2.31.1=h13024bc_3
  - binutils_impl_linux-64=2.43=h4bf12b8_4
  - bioconductor-biobase=2.66.0=r44h3df3fcb_0
  - bioconductor-biocgenerics=0.52.0=r44hdfd78af_3
  - bioconductor-biocparallel=1.40.0=r44he5774e6_1
  - bioconductor-data-packages=20250401=hdfd78af_0
  - bioconductor-delayedarray=0.32.0=r44h3df3fcb_1
  - bioconductor-deseq2=1.46.0=r44he5774e6_1
  - bioconductor-genomeinfodb=1.42.0=r44hdfd78af_2
  - bioconductor-genomeinfodbdata=1.2.13=r44hdfd78af_0
  - bioconductor-genomicranges=1.58.0=r44h3df3fcb_2
  - bioconductor-iranges=2.40.0=r44h3df3fcb_2
  - bioconductor-matrixgenerics=1.18.0=r44hdfd78af_0
  - bioconductor-s4arrays=1.6.0=r44h3df3fcb_1
  - bioconductor-s4vectors=0.44.0=r44h3df3fcb_2
  - bioconductor-sparsearray=1.6.0=r44h3df3fcb_1
  - bioconductor-summarizedexperiment=1.36.0=r44hdfd78af_0
  - bioconductor-ucsc.utils=1.2.0=r44h9ee0642_1
  - bioconductor-xvector=0.46.0=r44h15a9599_2
  - bioconductor-zlibbioc=1.52.0=r44h3df3fcb_2
  - blast=2.16.0=h66d330f_5
  - blosc=1.21.6=he440d0b_1
  - bowtie=1.3.1=py312hf8dbd9f_10
  - brotli-bin=1.1.0=hb9d3cd8_2
  - brotli-python=1.1.0=py312h2ec8cdc_2
  - bwidget=1.10.1=ha770c72_0
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - charset-normalizer=3.4.2=pyhd8ed1ab_0
  - click=8.1.8=pyh707e725_0
  - coin-or-cbc=2.10.12=h00e76a6_2
  - coin-or-cgl=0.60.9=h82e2f02_4
  - coin-or-clp=1.17.10=h8a7a1e7_1
  - coin-or-osi=0.108.11=h96cc833_4
  - coin-or-utils=2.11.12=h3a12e53_2
  - coincbc=2.10.12=2_metapackage
  - colorama=0.4.6=pyhd8ed1ab_1
  - coloredlogs=15.0.1=pyhd8ed1ab_4
  - conda-inject=1.3.2=pyhd8ed1ab_0
  - configargparse=1.7=pyhd8ed1ab_1
  - connection_pool=0.0.3=pyhd3deb0d_0
  - curl=8.13.0=h332b0f4_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.27=h54b06d7_7
  - dbus=1.13.6=h5008d03_3
  - docutils=0.21.2=pyhd8ed1ab_1
  - double-conversion=3.3.1=h5888daf_0
  - dpath=2.2.0=pyha770c72_0
  - eido=0.2.4=pyhd8ed1ab_0
  - entrez-direct=22.4=he881be0_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - expat=2.7.0=h5888daf_0
  - fastqc=0.12.1=hdfd78af_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.13.3=ha770c72_1
  - freexl=2.0.0=h9dce30a_2
  - fribidi=1.0.10=h36c2ea0_0
  - gcc_impl_linux-64=14.2.0=hdb7739f_2
  - geos=3.13.1=h97f6797_0
  - geotiff=1.7.4=h239500f_2
  - gfortran_impl_linux-64=14.2.0=h0ee6e4a_2
  - giflib=5.2.2=hd590300_0
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.44=pyhff2d567_0
  - graphite2=1.3.13=h59595ed_1003
  - gsl=2.7=he838d99_0
  - gxx_impl_linux-64=14.2.0=h2ead766_2
  - h2=4.2.0=pyhd8ed1ab_0
  - harfbuzz=11.2.1=h3beb420_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - htslib=1.21=h566b1c6_1
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - iniconfig=2.0.0=pyhd8ed1ab_1
  - isa-l=2.31.1=hb9d3cd8_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jq=1.5=0
  - json-c=0.18=h6688a6e_0
  - jsonschema=4.23.0=pyhd8ed1ab_1
  - jsonschema-specifications=2025.4.1=pyh29332c3_0
  - jupyter_core=5.7.2=py312h7900ff3_0
  - kernel-headers_linux-64=3.10.0=he073ed8_18
  - keyutils=1.6.1=h166bdaf_0
  - kraken2=2.14=pl5321h077b44d_0
  - krb5=1.21.3=h659f571_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - lerc=4.0.0=h0aef613_1
  - libarchive=3.7.7=h75ea233_4
  - libasprintf=0.24.1=h8e693c7_0
  - libblas=3.9.0=31_h59b9bed_openblas
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcblas=3.9.0=31_he106b2a_openblas
  - libclang-cpp20.1=20.1.5=default_h1df26ce_1
  - libclang13=20.1.5=default_he06ed0a_1
  - libcups=2.3.3=h4637d8d_4
  - libcurl=8.13.0=h332b0f4_0
  - libdeflate=1.23=h86f0d12_0
  - libdrm=2.4.124=hb9d3cd8_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libfreetype=2.13.3=ha770c72_1
  - libfreetype6=2.13.3=h48d6fc4_1
  - libgcc=14.2.0=h767d61c_2
  - libgcc-devel_linux-64=14.2.0=h9c4974d_102
  - libgcc-ng=14.2.0=h69a702a_2
  - libgdal-core=3.10.3=hab2de9c_5
  - libgettextpo=0.24.1=h5888daf_0
  - libgfortran=14.2.0=h69a702a_2
  - libgfortran-ng=14.2.0=h69a702a_2
  - libgfortran5=14.2.0=hf1ad2bd_2
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.84.1=h2ff4ddf_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=14.2.0=h767d61c_2
  - libhwloc=2.11.2=default_h0d58e46_1001
  - libiconv=1.18=h4ce23a2_1
  - libidn2=2.3.8=ha4ef2c3_0
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - libkml=1.3.0=hf539b9f_1021
  - liblapack=3.9.0=31_h7ac8fdf_openblas
  - liblapacke=3.9.0=31_he2f377e_openblas
  - libllvm20=20.1.5=he9d0ab4_0
  - liblzma=5.8.1=hb9d3cd8_0
  - libnghttp2=1.64.0=h161d5f1_0
  - libnsl=2.0.1=hd590300_0
  - libntlm=1.8=hb9d3cd8_0
  - libopenblas=0.3.29=pthreads_h94d23a6_0
  - libopengl=1.7.0=ha4b6fd6_2
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.47=h943b412_0
  - libpq=17.5=h27ae623_0
  - librttopo=1.1.0=hd718a1a_18
  - libsanitizer=14.2.0=hed042b8_2
  - libspatialite=5.1.0=he17ca71_14
  - libsqlite=3.49.1=hee588c1_2
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-devel_linux-64=14.2.0=h9c4974d_102
  - libstdcxx-ng=14.2.0=h4852527_2
  - libtiff=4.7.0=hd9ff511_4
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.9.2=h65c71a3_0
  - libxml2=2.13.8=h4bc477f_0
  - libxslt=1.1.39=h76b75d6_0
  - libzlib=1.3.1=hb9d3cd8_2
  - logmuse=0.2.8=pyhd8ed1ab_1
  - lz4-c=1.10.0=h5888daf_1
  - lzo=2.10=hd590300_1001
  - make=4.4.1=hb9d3cd8_2
  - markdown-it-py=3.0.0=pyhd8ed1ab_1
  - matplotlib-base=3.10.3=py312hd3ec401_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - minizip=4.0.10=h05a5f5f_0
  - munkres=1.0.7=py_1
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncbi-vdb=3.2.1=h9948957_0
  - ncurses=6.5=h2d0b736_3
  - openjdk=11.0.1=h516909a_1016
  - openjpeg=2.5.3=h5fbd93e_0
  - openldap=2.6.9=he970967_0
  - openssl=3.5.4=h26f9b46_0
  - ossuuid=1.6.2=h5888daf_1001
  - packaging=25.0=pyh29332c3_1
  - pandoc=3.7.0.2=ha770c72_0
  - pango=1.56.3=h9ac818e_1
  - parallel=20250422=ha770c72_0
  - patsy=1.0.1=pyhd8ed1ab_1
  - pbzip2=1.1.13=h1fcc475_2
  - pcre2=10.44=hc749103_2
  - pephubclient=0.4.4=pyhd8ed1ab_1
  - peppy=0.40.7=pyhd8ed1ab_2
  - perl=5.32.1=7_hd590300_perl5
  - perl-alien-build=2.84=pl5321h7b50bb2_1
  - perl-alien-libxml2=0.17=pl5321h577a1d6_1
  - perl-archive-tar=2.40=pl5321hdfd78af_0
  - perl-business-isbn=3.007=pl5321hdfd78af_0
  - perl-business-isbn-data=20210112.006=pl5321hdfd78af_0
  - perl-capture-tiny=0.48=pl5321hdfd78af_2
  - perl-carp=1.38=pl5321hdfd78af_4
  - perl-common-sense=3.75=pl5321hdfd78af_0
  - perl-compress-raw-bzip2=2.201=pl5321h87f3376_1
  - perl-compress-raw-zlib=2.105=pl5321h87f3376_0
  - perl-constant=1.33=pl5321hdfd78af_2
  - perl-data-dumper=2.183=pl5321hec16e2b_1
  - perl-encode=3.19=pl5321hec16e2b_1
  - perl-exporter=5.72=pl5321hdfd78af_2
  - perl-exporter-tiny=1.002002=pl5321hdfd78af_0
  - perl-extutils-makemaker=7.70=pl5321hd8ed1ab_0
  - perl-ffi-checklib=0.28=pl5321hdfd78af_0
  - perl-file-chdir=0.1010=pl5321hdfd78af_3
  - perl-file-path=2.18=pl5321hd8ed1ab_0
  - perl-file-temp=0.2304=pl5321hd8ed1ab_0
  - perl-file-which=1.24=pl5321hd8ed1ab_0
  - perl-importer=0.026=pl5321hdfd78af_0
  - perl-io-compress=2.201=pl5321h503566f_5
  - perl-io-zlib=1.14=pl5321hdfd78af_0
  - perl-json=4.10=pl5321hdfd78af_1
  - perl-json-xs=4.03=pl5321h9948957_4
  - perl-list-moreutils=0.430=pl5321hdfd78af_0
  - perl-list-moreutils-xs=0.430=pl5321h7b50bb2_5
  - perl-mime-base64=3.16=pl5321hec16e2b_2
  - perl-parent=0.236=pl5321hdfd78af_2
  - perl-path-tiny=0.122=pl5321hdfd78af_0
  - perl-pathtools=3.75=pl5321hec16e2b_3
  - perl-scalar-list-utils=1.62=pl5321hec16e2b_1
  - perl-scope-guard=0.21=pl5321hdfd78af_3
  - perl-sub-info=0.002=pl5321hdfd78af_1
  - perl-term-table=0.024=pl5321hdfd78af_0
  - perl-test2-suite=0.000163=pl5321hdfd78af_0
  - perl-types-serialiser=1.01=pl5321hdfd78af_0
  - perl-uri=5.12=pl5321hdfd78af_0
  - perl-xml-libxml=2.0210=pl5321hf886d80_0
  - perl-xml-namespacesupport=1.12=pl5321hdfd78af_1
  - perl-xml-sax=1.02=pl5321hdfd78af_1
  - perl-xml-sax-base=1.09=pl5321hdfd78af_1
  - pigz=2.8=hadc24fc_1
  - pip=25.1.1=pyh8b19718_0
  - pixman=0.46.0=h29eaf8c_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_2
  - plac=1.4.5=pyhd8ed1ab_0
  - platformdirs=4.3.7=pyh29332c3_0
  - pluggy=1.5.0=pyhd8ed1ab_1
  - popt=1.16=1
  - proj=9.6.0=h0054346_1
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.11.3=pyh3cfb1c2_0
  - pygments=2.19.1=pyhd8ed1ab_0
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pyside6=6.9.0=py312h91f0f75_0
  - pysocks=1.7.1=pyha55dd90_7
  - pytest=8.3.5=pyhd8ed1ab_0
  - python=3.12.10=h9e4cc4f_0_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-fastjsonschema=2.21.1=pyhd8ed1ab_0
  - python-isal=1.7.2=py312h66e93f0_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python-zlib-ng=0.5.1=py312h27ca174_0
  - python_abi=3.12=6_cp312
  - pytz=2025.2=pyhd8ed1ab_0
  - qhull=2020.2=h434a139_5
  - qt6-main=6.9.0=h8d00660_2
  - r-abind=1.4_5=r44hc72bb7e_1006
  - r-askpass=1.2.1=r44h2b5f3a1_0
  - r-backports=1.5.0=r44hb1dbf0f_1
  - r-base=4.4.3=h9c32bc2_0
  - r-base64enc=0.1_3=r44hb1dbf0f_1007
  - r-bh=1.87.0_1=r44hc72bb7e_0
  - r-bslib=0.9.0=r44hc72bb7e_0
  - r-cachem=1.1.0=r44hb1dbf0f_1
  - r-caret=6.0_94=r44hdb488b9_2
  - r-checkmate=2.3.2=r44hdb488b9_0
  - r-class=7.3_23=r44h2b5f3a1_0
  - r-cli=3.6.5=r44h93ab643_0
  - r-clock=0.7.3=r44h93ab643_0
  - r-cluster=2.1.8.1=r44hb67ce94_0
  - r-codetools=0.2_20=r44hc72bb7e_1
  - r-colorspace=2.1_1=r44hdb488b9_0
  - r-cpp11=0.5.2=r44h785f33e_1
  - r-crayon=1.5.3=r44hc72bb7e_1
  - r-curl=6.2.2=r44h2700575_0
  - r-data.table=1.17.6=r44he23165d_0
  - r-deldir=2.0_4=r44hbcb9c34_1
  - r-diagram=1.6.5=r44ha770c72_3
  - r-digest=0.6.37=r44h0d4f4ea_0
  - r-dplyr=1.1.4=r44h0d4f4ea_1
  - r-e1071=1.7_16=r44h93ab643_0
  - r-ellipsis=0.3.2=r44hb1dbf0f_3
  - r-evaluate=1.0.3=r44hc72bb7e_0
  - r-fansi=1.0.6=r44hb1dbf0f_1
  - r-farver=2.1.2=r44ha18555a_1
  - r-fastmap=1.2.0=r44ha18555a_1
  - r-fontawesome=0.5.3=r44hc72bb7e_0
  - r-foreach=1.5.2=r44hc72bb7e_3
  - r-foreign=0.8_90=r44h2b5f3a1_0
  - r-formatr=1.14=r44hc72bb7e_2
  - r-formula=1.2_5=r44hc72bb7e_2
  - r-fs=1.6.6=r44h93ab643_0
  - r-futile.logger=1.4.3=r44hc72bb7e_1006
  - r-futile.options=1.0.1=r44hc72bb7e_1005
  - r-future=1.58.0=r44h785f33e_0
  - r-future.apply=1.20.0=r44hc72bb7e_0
  - r-generics=0.1.4=r44hc72bb7e_0
  - r-ggplot2=3.5.2=r44hc72bb7e_0
  - r-globals=0.18.0=r44hc72bb7e_0
  - r-glue=1.8.0=r44h2b5f3a1_0
  - r-gower=1.0.1=r44hb1dbf0f_2
  - r-gridextra=2.3=r44hc72bb7e_1006
  - r-gtable=0.3.6=r44hc72bb7e_0
  - r-hardhat=1.4.1=r44hc72bb7e_0
  - r-highr=0.11=r44hc72bb7e_1
  - r-hmisc=5.2_3=r44hb67ce94_0
  - r-htmltable=2.4.3=r44hc72bb7e_0
  - r-htmltools=0.5.8.1=r44ha18555a_1
  - r-htmlwidgets=1.6.4=r44h785f33e_3
  - r-httr=1.4.7=r44hc72bb7e_1
  - r-interp=1.1_6=r44ha936806_1
  - r-ipred=0.9_15=r44hdb488b9_1
  - r-isoband=0.2.7=r44ha18555a_3
  - r-iterators=1.0.14=r44hc72bb7e_3
  - r-jpeg=0.1_11=r44hc5f1ce6_0
  - r-jquerylib=0.1.4=r44hc72bb7e_3
  - r-jsonlite=2.0.0=r44h2b5f3a1_0
  - r-kernsmooth=2.23_26=r44h8461fee_0
  - r-knitr=1.50=r44hc72bb7e_0
  - r-labeling=0.4.3=r44hc72bb7e_1
  - r-lambda.r=1.2.4=r44hc72bb7e_4
  - r-lattice=0.22_7=r44h2b5f3a1_0
  - r-latticeextra=0.6_30=r44hc72bb7e_3
  - r-lava=1.8.1=r44hc72bb7e_0
  - r-lifecycle=1.0.4=r44hc72bb7e_1
  - r-listenv=0.9.1=r44hc72bb7e_1
  - r-locfit=1.5_9.12=r44h2b5f3a1_0
  - r-lubridate=1.9.4=r44h2b5f3a1_0
  - r-magrittr=2.0.3=r44hb1dbf0f_3
  - r-mass=7.3_64=r44h2b5f3a1_0
  - r-matrix=1.7_3=r44h2ae2be5_0
  - r-matrixstats=1.5.0=r44h2b5f3a1_0
  - r-memoise=2.0.1=r44hc72bb7e_3
  - r-mgcv=1.9_3=r44h2ae2be5_0
  - r-mime=0.13=r44h2b5f3a1_0
  - r-modelmetrics=1.2.2.2=r44h0d4f4ea_4
  - r-modeva=3.34=r44hc72bb7e_0
  - r-munsell=0.5.1=r44hc72bb7e_1
  - r-nlme=3.1_168=r44hb67ce94_0
  - r-nnet=7.3_20=r44h2b5f3a1_0
  - r-numderiv=2016.8_1.1=r44hc72bb7e_6
  - r-openssl=2.3.3=r44he8289e2_0
  - r-parallelly=1.45.0=r44h2b5f3a1_0
  - r-pillar=1.10.2=r44hc72bb7e_0
  - r-pkgconfig=2.0.3=r44hc72bb7e_4
  - r-plyr=1.8.9=r44ha18555a_1
  - r-png=0.1_8=r44h21f035c_2
  - r-proc=1.18.5=r44ha18555a_1
  - r-prodlim=2025.04.28=r44h93ab643_0
  - r-progressr=0.15.1=r44hc72bb7e_0
  - r-proxy=0.4_27=r44hb1dbf0f_3
  - r-purrr=1.0.4=r44h2b5f3a1_0
  - r-r6=2.6.1=r44hc72bb7e_0
  - r-randomforest=4.7_1.2=r44hb67ce94_0
  - r-rappdirs=0.3.3=r44hb1dbf0f_3
  - r-rcolorbrewer=1.1_3=r44h785f33e_3
  - r-rcpp=1.0.14=r44h93ab643_0
  - r-rcpparmadillo=14.4.2_1=r44hc2d650c_0
  - r-rcppeigen=0.3.4.0.2=r44hb79369c_0
  - r-recipes=1.3.1=r44hc72bb7e_0
  - r-reshape2=1.4.4=r44h0d4f4ea_4
  - r-rlang=1.1.6=r44h93ab643_0
  - r-rmarkdown=2.29=r44hc72bb7e_0
  - r-rpart=4.1.24=r44h2b5f3a1_0
  - r-rstudioapi=0.17.1=r44hc72bb7e_0
  - r-sass=0.4.10=r44h93ab643_0
  - r-scales=1.4.0=r44hc72bb7e_0
  - r-shape=1.4.6.1=r44ha770c72_1
  - r-snow=0.4_4=r44hc72bb7e_3
  - r-sparsevctrs=0.3.4=r44h2b5f3a1_0
  - r-squarem=2021.1=r44hc72bb7e_3
  - r-stringi=1.8.7=r44h3c328a7_0
  - r-stringr=1.5.1=r44h785f33e_1
  - r-survival=3.8_3=r44h2b5f3a1_0
  - r-sys=3.4.3=r44h2b5f3a1_0
  - r-terra=1.8_42=r44hb42e7d3_2
  - r-tibble=3.3.0=r44h2b5f3a1_0
  - r-tidyr=1.3.1=r44h0d4f4ea_1
  - r-tidyselect=1.2.1=r44hc72bb7e_1
  - r-timechange=0.3.0=r44ha18555a_1
  - r-timedate=4041.110=r44hc72bb7e_0
  - r-tinytex=0.57=r44hc72bb7e_0
  - r-tzdb=0.5.0=r44h93ab643_0
  - r-utf8=1.2.6=r44h2b5f3a1_0
  - r-vctrs=0.6.5=r44h0d4f4ea_1
  - r-viridis=0.6.5=r44hc72bb7e_1
  - r-viridislite=0.4.2=r44hc72bb7e_2
  - r-withr=3.0.2=r44hc72bb7e_0
  - r-xfun=0.52=r44h93ab643_0
  - r-yaml=2.3.10=r44hdb488b9_0
  - readline=8.2=h8c095d6_2
  - referencing=0.36.2=pyh29332c3_0
  - requests=2.32.3=pyhd8ed1ab_1
  - reretry=0.11.8=pyhd8ed1ab_1
  - rich=14.0.0=pyh29332c3_0
  - rpsbproc=0.5.0=hd6d6fdc_3
  - rsync=3.4.1=h81c0278_2
  - samtools=1.21=h96c455f_1
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - sed=4.9=h6688a6e_0
  - seqkit=2.10.0=h9ee0642_0
  - setuptools=80.1.0=pyhff2d567_0
  - shellingham=1.5.4=pyhd8ed1ab_1
  - six=1.17.0=pyhd8ed1ab_0
  - slack-sdk=3.35.0=pyhd8ed1ab_0
  - slack_sdk=3.35.0=hd8ed1ab_0
  - smart_open=7.1.0=pyhd8ed1ab_0
  - smmap=5.0.2=pyhd8ed1ab_0
  - snakemake=9.3.3=hdfd78af_0
  - snakemake-interface-common=1.17.4=pyhdfd78af_0
  - snakemake-interface-executor-plugins=9.3.5=pyhdfd78af_0
  - snakemake-interface-logger-plugins=1.2.3=pyhdfd78af_0
  - snakemake-interface-report-plugins=1.1.0=pyhdfd78af_0
  - snakemake-interface-storage-plugins=4.2.1=pyhdfd78af_0
  - snakemake-minimal=9.3.3=pyhdfd78af_0
  - snappy=1.2.1=h8bd8927_1
  - sqlite=3.49.1=h9eae976_2
  - sra-tools=3.2.1=h4304569_0
  - sysroot_linux-64=2.17=h0157908_18
  - tabulate=0.9.0=pyhd8ed1ab_2
  - tar=1.34=hb2e2bae_1
  - tbb=2022.1.0=h4ce085d_0
  - throttler=1.2.2=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - tktable=2.10=h8bc8fbc_6
  - toml=0.10.2=pyhd8ed1ab_1
  - tomli=2.2.1=pyhd8ed1ab_1
  - tomlkit=0.13.3=pyha770c72_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - trim-galore=0.6.10=hdfd78af_1
  - typer=0.15.3=pyhf21524f_0
  - typer-slim=0.15.3=pyh29332c3_0
  - typer-slim-standard=0.15.3=h1a15894_0
  - typing-extensions=4.13.2=h0e9735f_0
  - typing-inspection=0.4.0=pyhd8ed1ab_0
  - typing_extensions=4.13.2=pyh29332c3_0
  - tzdata=2025b=h78e105d_0
  - ubiquerg=0.8.0=pyhd8ed1ab_0
  - uriparser=0.9.8=hac33072_0
  - urllib3=2.4.0=pyhd8ed1ab_0
  - veracitools=0.1.3=py_0
  - wayland=1.23.1=h3e06ad9_1
  - wget=1.21.4=hda4d442_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xcb-util=0.4.1=hb711507_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xerces-c=3.2.5=h988505b_2
  - xkeyboard-config=2.44=hb9d3cd8_0
  - xmltodict=0.14.2=pyhd8ed1ab_1
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - xxhash=0.8.3=hb47aa4a_0
  - yaml=0.2.5=h7f98852_2
  - yq=3.4.3=pyhe01879c_2
  - yte=1.7.0=pyha770c72_1
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
    - blinker==1.9.0
    - brotli==1.1.0
    - cffi==1.17.1
    - contourpy==1.3.2
    - cryptography==45.0.4
    - cutadapt==5.0
    - dnaio==1.2.2
    - evatool==0.1.21
    - flask==3.1.1
    - fonttools==4.58.0
    - humanfriendly==10.0
    - immutables==0.21
    - isal==1.7.2
    - itsdangerous==2.2.0
    - jupyter-core==5.7.2
    - kiwisolver==1.4.8
    - markupsafe==3.0.2
    - matplotlib==3.10.3
    - numpy==2.2.5
    - pandas==2.2.3
    - pdf2image==1.17.0
    - pillow==11.2.1
    - poppler-utils==0.1.0
    - psutil==7.0.0
    - pulp==2.8.0
    - pydantic-core==2.33.1
    - pymysql==1.1.1
    - pyyaml==6.0.2
    - rpds-py==0.24.0
    - scipy==1.15.2
    - statsmodels==0.14.4
    - tornado==6.5
    - unicodedata2==16.0.0
    - werkzeug==3.1.3
    - wrapt==1.17.2
    - xopen==2.0.2
    - zlib-ng==0.5.1
    - zstandard==0.23.0
prefix: /home/huangrf/software/mambaforge/envs/EVdb
